#!/bin/bash
# reference: https://github.com/google/macops/blob/master/keychainminder/Package/postinstall

[[ $3 != "/" ]] && exit 0

user=$(/usr/bin/stat -f '%u' /dev/console)
[[ -z "$user" ]] && exit 0
/bin/launchctl asuser ${user} /bin/launchctl load /Library/LaunchAgents/com.chilcote.vfused.plist

exit 0